########## In RStudio ########
# pick existing directory as new project
getwd()    # to confirm current working directory
save()    # save into .rda file, .RData is also fine but less preferred
ggsave("figs/barplot.png")    # save a plot generated by ggplot2 to a dir called "figs"

url<- "http://raw.githubusercontent.com/rafalab/dslabs/master/inst/extdata/murders.csv"
dest_file<- "data/murders.csv"
download.file(url,destfile = dest_file)
